"""room_messages_model

Revision ID: 23abba3af76d
Revises: 55dcbdee5a78
Create Date: 2018-01-18 09:22:53.206358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23abba3af76d'
down_revision = '55dcbdee5a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
